# MPLAB IDE generated this makefile for use with GNU make.
# Project: Boss level lab3.mcp
# Date: Tue Oct 06 20:06:07 2020

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Boss\ level\ lab3.cof : Boss\ level\ lab3.o
	$(CC) /p18F4550 "Boss level lab3.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Boss level lab3.cof" /M"Boss level lab3.map" /W /x

Boss\ level\ lab3.o : Boss\ level\ lab3.asm ../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/p18F4550.inc
	$(AS) /q /p18F4550 "Boss level lab3.asm" /l"Boss level lab3.lst" /e"Boss level lab3.err" /d__DEBUG=1

clean : 
	$(CC) "Boss level lab3.o" "Boss level lab3.hex" "Boss level lab3.err" "Boss level lab3.lst" "Boss level lab3.cof"

